### ISSUE TITLE
Misleading syntax in first Deliverable

### ISSUE THREAD

**Issue by ErinRRose** [learn-co-curriculum/react-information-flow-code-along#26]
The but in the first deliverable is confusing and it seems as though you only need to do that part not the part before it.

**Comment by lizbur10** [comment]
Hi @ErinRRose ! Thanks for flagging this! The instructions have been updated. Note that you may not see the change in your Canvas course, but it will be present for students moving forward.

Thanks for contributing to the Flatiron School curriculum 💙
